import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000000',
    zIndex: 1000,
  },
  content: {
    flex: 1,
    backgroundColor: '#000000',
    width: '100%',
    height: '100%',
    marginTop: 0,
    marginBottom: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  scrollView: {
    flex: 1,
    height: '100%',
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 16,
  },
  heroSection: {
    height: 400, // Altura fija en lugar de porcentaje
    position: 'relative',
    justifyContent: 'flex-end',
    paddingBottom: 0,
  },
  trailerBackground: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  trailerBackgroundVideo: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  backdropImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  backdropOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  heroContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    paddingBottom: 20,
    zIndex: 10,
  },
  heroInfo: {
    maxWidth: '85%',
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  heroMetadata: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  heroYear: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  heroSeparator: {
    color: '#FFFFFF',
    fontSize: 16,
    marginHorizontal: 8,
  },
  heroRuntime: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  heroAgeRating: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  heroRating: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  heroOverview: {
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 26,
    marginTop: 0,
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    fontWeight: '400',
  },
  skeletonContainer: {
    marginTop: 0,
    marginBottom: 16,
    gap: 8,
  },
  skeletonLine: {
    height: 16,
    backgroundColor: '#2A2A2A',
    borderRadius: 4,
    width: '90%',
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    marginBottom: 16,
  },
  playButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 6,
    gap: 8,
  },
  playButtonText: {
    color: '#000000',
    fontSize: 16,
    fontWeight: '600',
  },
  myListButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(109, 109, 110, 0.7)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 6,
    gap: 8,
  },
  myListButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(109, 109, 110, 0.7)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 6,
    gap: 8,
  },
  downloadButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  trailerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(109, 109, 110, 0.7)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 6,
    gap: 8,
  },
  trailerButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  trailerCloseButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 2,
  },
  trailerCloseText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
  detailsSection: {
    padding: 20,
    backgroundColor: '#141414',
    marginTop: 0,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  detailLabel: {
    color: '#999999',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
    minWidth: 100,
  },
  detailValue: {
    color: '#FFFFFF',
    fontSize: 16,
    flex: 1,
  },
  relatedSection: {
    backgroundColor: '#141414',
    paddingVertical: 20,
  },
  relatedTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  relatedLoading: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 200,
  },
  relatedCard: {
    marginRight: 12,
    borderRadius: 8,
    overflow: 'hidden',
  },
  relatedPoster: {
    width: 120,
    height: 180,
  },
  noRelatedContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 200,
    paddingHorizontal: 20,
  },
  noRelatedText: {
    color: '#999999',
    fontSize: 16,
    textAlign: 'center',
  },
  // Streaming styles
  streamingSection: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  streamingHeader: {
    marginBottom: 16,
  },
  streamingTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  streamingSubtitle: {
    fontSize: 14,
    color: '#999999',
    fontStyle: 'italic',
  },
  streamingLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  streamingLoadingText: {
    color: '#FFFFFF',
    marginLeft: 8,
    fontSize: 14,
  },
  seasonsContainer: {
    marginBottom: 20,
  },
  seasonPicker: {
    marginBottom: 12,
    position: 'relative',
  },
  seasonPickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 6,
  },
  seasonPickerButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  seasonPickerList: {
    position: 'absolute',
    top: 44,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(34, 34, 34, 0.95)',
    borderRadius: 6,
    overflow: 'hidden',
    zIndex: 100,
    // Elevation for Android to ensure the list sits above other content
    elevation: 12,
    // Shadow for iOS/web for visual separation
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  seasonModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  seasonModalContent: {
    width: '90%',
    maxWidth: 420,
    backgroundColor: '#222',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    overflow: 'hidden',
  },
  seasonModalHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  seasonModalHeaderText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  seasonModalList: {
    maxHeight: 360,
  },
  seasonPickerItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  seasonPickerItemText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  seasonContainer: {
    marginBottom: 24,
  },
  streamingSeasonHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  streamingSeasonTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  seasonEpisodeCount: {
    fontSize: 14,
    color: '#999999',
  },
  episodesGrid: {
    gap: 8,
  },
  episodeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  episodeNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E50914',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  episodeNumberText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  episodeInfo: {
    flex: 1,
    marginRight: 12,
  },
  episodeThumb: {
    width: 72,
    height: 40,
    borderRadius: 6,
    marginRight: 12,
    backgroundColor: '#222'
  },
  episodeTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  episodeDescription: {
    color: '#999999',
    fontSize: 12,
    lineHeight: 16,
  },
  episodePlayButton: {
    padding: 4,
  },
  noEpisodesContainer: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  noEpisodesText: {
    color: '#999999',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 8,
  },
  noEpisodesSubtext: {
    color: '#666666',
    fontSize: 12,
    textAlign: 'center',
  },
  // Estilos para el estado del anime
  animeStatusContainer: {
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusLabel: {
    fontSize: 16,
    color: '#999999',
    fontWeight: '600',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#333333',
  },
  statusBadgeAiring: {
    backgroundColor: '#ff4444',
  },
  statusBadgeFinished: {
    backgroundColor: '#44ff44',
  },
  statusText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  statusTextAiring: {
    color: '#FFFFFF',
  },
  statusTextFinished: {
    color: '#000000',
  },
  // Estilos para información compacta
  compactInfoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  compactInfoItem: {
    flex: 1,
    minWidth: '30%',
    marginBottom: 12,
    paddingRight: 12,
  },
  compactInfoLabel: {
    fontSize: 12,
    color: '#999999',
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  compactInfoValue: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
});

// ── HERO STYLES ─────────────────────────────────────────────────
export const heroStyles = StyleSheet.create({
  heroSection: {
    height: 500,
    position: 'relative',
    overflow: 'hidden',
    justifyContent: 'flex-end',
    backgroundColor: '#0a0a0a',
  },
  backdropImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    // objectPosition se aplica inline de forma dinámica (ver JSX)
  },
  gradient: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  heroContent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 24,
    paddingVertical: 72,
    justifyContent: 'center',
    transform: [{ translateY: 56 }],
    maxWidth: 740,        // evita que el texto flote en pantallas ultrawides
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 18,
  },
  ratingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,215,0,0.15)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,215,0,0.3)',
  },
  ratingText: { color: '#FFD700', fontSize: 11, fontWeight: '800' },
  metaText: { color: 'rgba(255,255,255,0.6)', fontSize: 12, fontWeight: '500' },
  dot: { color: 'rgba(255,255,255,0.3)', fontSize: 12 },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  statusPillText: { color: '#fff', fontSize: 11, fontWeight: '700', letterSpacing: 0.3 },
  title: {
    color: '#FFFFFF',
    fontWeight: '900',
    letterSpacing: -0.7,
    marginBottom: 18,
    lineHeight: 40,
    textShadowColor: 'rgba(0,0,0,0.95)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  genreRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 18,
  },
  genreChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  genreChipText: { color: 'rgba(255,255,255,0.78)', fontSize: 11, fontWeight: '600' },
  overview: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: 22,
    marginBottom: 28,
    maxWidth: 500,        // limita el ancho del texto en desktop
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flexWrap: 'wrap',
  },
  btnPlay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    paddingVertical: 11,
    borderRadius: 6,
  },
  btnPlayText: { color: '#000', fontSize: 15, fontWeight: '800', letterSpacing: -0.2 },
  btnSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: 'rgba(60,60,60,0.85)',
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  btnSecondaryText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  btnIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  btnIconText: { color: 'rgba(255,255,255,0.8)', fontSize: 13, fontWeight: '600' },
});

// ── CONTINUE WATCHING CARD ──────────────────────────────────────
export const continueStyles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#181818',
    marginHorizontal: 16,
    marginTop: -52,
    marginBottom: 4,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.09)',
    minHeight: 84,
    position: 'relative',
    zIndex: 5,
    shadowColor: '#000',
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  thumb: {
    width: 116,
    backgroundColor: '#111',
    position: 'relative',
    overflow: 'hidden',
    alignSelf: 'stretch',
  },
  thumbOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  info: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    justifyContent: 'center',
    gap: 3,
  },
  label: {
    color: '#E50914',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  epTitle: { color: '#FFFFFF', fontSize: 13, fontWeight: '700', lineHeight: 18 },
  duration: { color: 'rgba(255,255,255,0.35)', fontSize: 11, marginTop: 2 },
  // Botón horizontal premium
  playBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#E50914',
    paddingHorizontal: 18,
    paddingVertical: 12,
    marginRight: 0,
    alignSelf: 'stretch',
    justifyContent: 'center',
    minWidth: 112,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: 'rgba(0,0,0,0.35)',
    borderRadius: 0,
  },
  playBtnText: { color: '#fff', fontSize: 12, fontWeight: '800', letterSpacing: 0.2 },
});

// ── INFO RÁPIDA ─────────────────────────────────────────────────
export const infoStyles = StyleSheet.create({
  section: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#141414',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  cell: {
    flex: 1,
    minWidth: 80,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  cellLabel: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  cellValue: { color: '#fff', fontSize: 14, fontWeight: '700', lineHeight: 18 },
  statusPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  statusPillText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  genreRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  genreChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  genreChipText: { color: 'rgba(255,255,255,0.65)', fontSize: 12, fontWeight: '500' },
});

// ── EPISODE STYLES ──────────────────────────────────────────────
export const epStyles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 5,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.06)',
    gap: 12,
  },
  thumb: {
    width: 92,
    height: 56,
    borderRadius: 6,
    backgroundColor: '#1a1a1a',
  },
  numBadge: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: 'rgba(229,9,20,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(229,9,20,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  numText: { color: '#E50914', fontSize: 15, fontWeight: '800' },
  info: { flex: 1, gap: 2 },
  num: {
    color: 'rgba(255,255,255,0.32)',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  title: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
  },
  desc: { color: 'rgba(255,255,255,0.35)', fontSize: 11, lineHeight: 15 },
  playWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#E50914',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#E50914',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.45,
    shadowRadius: 5,
  },
});

// ── SIMILAR SECTION ─────────────────────────────────────────────
export const simStyles = StyleSheet.create({
  section: {
    backgroundColor: '#0f0f0f',
    paddingBottom: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  accentBar: {
    width: 3,
    height: 18,
    backgroundColor: '#E50914',
    borderRadius: 2,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  card: {
    width: 110,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#1c1c1c',
  },
  poster: {
    width: 110,
    height: 160,
  },
  emptyWrap: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  emptyText: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 12,
    fontStyle: 'italic',
    letterSpacing: 0.1,
  },
});
